'use strict';
(function(I){
class Game {
  constructor(canvas){this.renderer=new I.Renderer(canvas);this.world=new I.World();this.player={x:384.5,y:18.05,z:384.5,yaw:0.20,pitch:-0.10,vy:0,hp:100,mana:100,hunger:100,ground:false,moving:false};this.time=210;this.mode='survival';this.active=false;this.modal=true;this.enemies=[];this.projectiles=[];this.particles=[];this.remotePlayers={};this.inventory={};this.hotbar=['pick','sword','pistol','fire','frost','dirt','planks','lamp'];this.slot=0;this.cooldown=0;this.flash=0;this.mining=null;this.target=null;this.input={x:0,z:0,jump:false,attack:false,mine:false,sprint:false,keys:{}};this.visible=this.world.loadAround(this.player.x,this.player.z,true);this.nextId=1;this.saveTimer=0;this.spawnTimer=0;this.tick=0;this.kills=0;this.bosses=[];this.events=[];this.lastTime=0;this.fps=60;this.frameMS=16.7;this.hitMarker=0;this.swing=0;this.streamTimer=0;this.settings=this.readSettings();this.applySettings();this.audio=null;this.ui=null;this.network=null;this.lastError=null;
    this.hazards=[];this.level=1;this.xp=0;this.explored=[];this.magazines={};this.reloading=null;this.loop=this.loop.bind(this);requestAnimationFrame(this.loop);
  }
  readSettings(){
    const defaults={version:3,quality:'balanced',resolution:'auto',fps:60,fov:74,sensitivity:1,sound:true,invert:false,joystickSize:1,buttonSize:1,hudSize:1,opacity:.82,leftHand:false,showFps:false,stickMode:'fixed',deadzone:.06,autoSprint:true,adaptive:true,layout:{}};
    try{const old=JSON.parse(localStorage.getItem('iskra.settings')||'{}'),s={...defaults,...old};if(old.version!==3){s.layout={};s.version=3;}s.sensitivity=I.clamp(+s.sensitivity||1,.25,2.5);s.deadzone=I.clamp(+s.deadzone||0,0,.22);return s;}catch(e){return defaults;}
  }
  applySettings(){const q=this.settings.quality;this.world.radius=q==='low'?2:q==='high'?4:3;this.renderer.quality=q==='low'?.65:q==='high'?1:.85;this.renderer.detail=q==='low'?0:q==='high'?2:1;this.renderer.adaptive=this.settings.adaptive;this.renderer.resolution=this.settings.resolution||'auto';this.renderer.fov=this.settings.fov||74;this.renderer.resize();if(this.ui)this.ui.applyControls();}
  setSettings(data){Object.assign(this.settings,data);this.applySettings();localStorage.setItem('iskra.settings',JSON.stringify(this.settings));}
  selectedItem(){return this.hotbar[this.slot]||'pick';}
  actionInfo(){const it=I.ITEMS[this.selectedItem()];if(this.reloading?.id===this.selectedItem())return {icon:'ammo',label:'Зарядка…'};return {tool:{icon:'pick',label:'Копать'},melee:{icon:'sword',label:'Удар'},gun:{icon:'aim',label:'Огонь'},magic:{icon:it.icon,label:['bow','crossbow'].includes(this.selectedItem())?'Выстрел':this.selectedItem()==='grenade'?'Бросок':'Заклинание'},block:{icon:'block',label:'Поставить'},summon:{icon:'boss',label:'Призвать'},consumable:{icon:it.icon,label:'Использовать'}}[it.kind]||{icon:'aim',label:'Действие'};}
  selectSlot(slot){this.slot=I.clamp(slot|0,0,7);this.mining=null;this.swing=0;this.swap=.18;if(this.reloading&&this.reloading.id!==this.selectedItem())this.reloading=null;}

  direction(){const p=this.player,c=Math.cos(p.pitch);return [Math.sin(p.yaw)*c,Math.sin(p.pitch),-Math.cos(p.yaw)*c];}
  eye(){return [this.player.x,this.player.y+1.58,this.player.z];}
  start(mode,resume=false){if(this.network)this.network.stop();for(const c of this.world.chunks.values())this.renderer.freeChunk(c);this.world=new I.World();this.applySettings();this.mode=mode;this.inventory={pick:1,axe:1,sword:1,pistol:1,fire:1,frost:1,dirt:32,stone:16,wood:12,planks:24,lamp:4,ammo:100,food:6,potion:2,iron:0,crystal:0,sand:0,ice:0};if(mode!=='survival')for(const id of Object.keys(I.ITEMS))this.inventory[id]=I.ITEMS[id].kind==='block'?999:I.ITEMS[id].kind==='resource'?600:99;
    this.player={x:384.5,y:18.05,z:384.5,yaw:0.20,pitch:-0.10,vy:0,hp:100,mana:100,hunger:100,ground:false,moving:false};this.time=135;this.hotbar=['pick','sword','pistol','fire','frost','dirt','planks','lamp'];this.slot=0;this.enemies=[];this.projectiles=[];this.particles=[];this.kills=0;this.bosses=[];this.cooldown=0;this.mining=null;this.spawnTimer=5;this.saveTimer=0;this.remotePlayers={};this.hazards=[];this.swing=0;this.hitMarker=0;this.streamTimer=0;this.renderer.resetStreaming?.();this.level=1;this.xp=0;this.explored=['4,4'];this.magazines={};this.reloading=null;
    if(resume){try{const data=JSON.parse(localStorage.getItem('iskra.save.'+mode)||'null');if(data)this.restore(data);}catch(e){this.notify('Сохранение не прочитано. Начат новый мир.');}}
    this.visible=this.world.loadAround(this.player.x,this.player.z,true);this.active=true;this.modal=false;if(mode!=='creative')for(const type of ['slime','wolf','golem','wisp'])this.spawnEnemy(type);this.sound('start');this.notify(mode==='creative'?'Творчество: двойное нажатие прыжка — полёт.':mode==='hunt'?'Охота: оружие готово. Призывай боссов через рюкзак.':'Собирай ресурсы, построй убежище и исследуй руины.');if(this.ui)this.ui.showGame();
  }
  snapshot(){return {version:1,mode:this.mode,world:this.world.export(),player:{...this.player,vy:0},inventory:this.inventory,hotbar:this.hotbar,slot:this.slot,time:this.time,kills:this.kills,bosses:this.bosses,level:this.level,xp:this.xp,explored:this.explored,magazines:this.magazines,mods:this.mods||[]};}
  xpNeeded(){return 60+this.level*40;}
  gainXP(n){if(this.mode!=='survival'||!Number.isFinite(n)||n<=0||this.network?.role==='client')return;this.xp+=Math.floor(n);while(this.level<20&&this.xp>=this.xpNeeded()){this.xp-=this.xpNeeded();this.level++;this.player.hp=Math.min(100,this.player.hp+15);this.player.mana=100;this.notify('Уровень '+this.level+'! Новые рецепты и реликвии доступны.');this.sound('craft');}if(this.level>=20)this.xp=Math.min(this.xp,this.xpNeeded()-1);if(this.ui)this.ui.inventoryDirty=true;}
  recipeRequirement(recipe){if(this.mode!=='survival'||!recipe.requires)return '';if(this.level<(recipe.requires.level||1))return 'Нужен уровень '+recipe.requires.level;if(recipe.requires.boss&&!this.bosses.includes(recipe.requires.boss))return 'Сначала победи: '+I.ENEMIES[recipe.requires.boss].name;return '';}
  bossRequirement(type,needRelic=true){const d=I.ENEMIES[type];if(!d?.boss)return 'Неизвестный босс.';if(this.mode!=='survival')return '';if(this.level<d.level)return 'Нужен уровень '+d.level;if(d.previous&&!this.bosses.includes(d.previous))return 'Сначала победи: '+I.ENEMIES[d.previous].name;if(needRelic&&(this.inventory[d.relic]||0)<1)return 'Создай предмет призыва: '+I.ITEMS[d.relic].name;return '';}
  reload(){const id=this.selectedItem(),item=I.ITEMS[id];if(this.reloading||!item.magazine||this.mode==='creative')return false;const ammo=item.ammoItem||'ammo';if((this.inventory[ammo]||0)<(item.ammo||1)){this.notify('Нет боеприпасов для перезарядки.');return false;}const total=item.reload||1.5;this.reloading={id,time:total,total};this.sound('place');return true;}
  restore(data){if(data.version!==1||!data.world||!data.player)throw Error('Неизвестный формат сохранения.');const p=data.player;if(![p.x,p.y,p.z,p.yaw,p.pitch,p.hp,p.mana,p.hunger].every(Number.isFinite)||p.x<1||p.z<1||p.x>766||p.z>766||p.y<1||p.y>100)throw Error('Некорректная позиция.');for(const c of this.world.chunks.values())this.renderer.freeChunk(c);this.world=new I.World(data.world.seed);this.world.restore(data.world);this.applySettings();Object.assign(this.player,p,{vy:0});this.player.hp=I.clamp(p.hp,1,100);this.player.mana=I.clamp(p.mana,0,100);this.player.hunger=I.clamp(p.hunger,0,100);for(const [id,n] of Object.entries(data.inventory||{}))if(I.ITEMS[id]&&Number.isFinite(n)&&n>=0&&n<=100000)this.inventory[id]=Math.floor(n);if(Array.isArray(data.hotbar)&&data.hotbar.length===8&&data.hotbar.every(id=>I.ITEMS[id]))this.hotbar=data.hotbar;this.slot=I.clamp(data.slot|0,0,7);this.time=Number.isFinite(data.time)?data.time:210;this.kills=data.kills|0;this.bosses=Array.isArray(data.bosses)?data.bosses.filter(x=>I.ENEMIES[x]?.boss):[];this.level=I.clamp(data.level|0,1,20);this.xp=I.clamp(Number.isFinite(data.xp)?data.xp:0,0,this.xpNeeded()-1);this.explored=Array.isArray(data.explored)?data.explored.filter(x=>typeof x==='string'&&/^\d,\d$/.test(x)).slice(0,64):['4,4'];this.magazines={};for(const [id,n] of Object.entries(data.magazines||{}))if(I.ITEMS[id]?.magazine&&Number.isFinite(n))this.magazines[id]=I.clamp(n|0,0,I.ITEMS[id].magazine);this.reloading=null;if(this.world.collision(this.player.x,this.player.y,this.player.z))this.player.y=this.world.surface(this.player.x,this.player.z)+0.05;}
  save(silent=false){if(!this.active)return false;if(this.network&&this.network.role==='client'){if(!silent)this.notify('Мир сохраняет хозяин комнаты.');return false;}try{localStorage.setItem('iskra.save.'+this.mode,JSON.stringify(this.snapshot()));if(!silent)this.notify('Мир сохранён на устройстве.');return true;}catch(e){this.notify('Не удалось сохранить: мало места на устройстве.');return false;}}
  loop(now){
    if(this.lastTime&&now-this.lastTime<1000/(this.settings.fps||60)-1){requestAnimationFrame(this.loop);return;}
    try{const raw=this.lastTime?(now-this.lastTime)/1000:1/60,dt=Math.min(raw,.05);this.lastTime=now;this.fps=this.fps*.92+(1/Math.max(raw,.001))*.08;this.frameMS=raw*1000;this.tick++;this.update(dt);this.renderer.render(this);this.renderer.adapt?.(this.frameMS,this.settings.fps||60,this.active&&!this.modal);if(this.ui&&(this.tick%5===0||this.actionChanged)){this.ui.update();this.actionChanged=false;}}catch(e){if(this.lastError!==e.message){this.lastError=e.message;console.error(e);this.notify('Ошибка движка: '+e.message);}}
    requestAnimationFrame(this.loop);
  }
  update(dt){const p=this.player;this.cooldown=Math.max(0,this.cooldown-dt);this.flash=Math.max(0,this.flash-dt);this.hitMarker=Math.max(0,this.hitMarker-dt);this.swing=Math.max(0,this.swing-dt);this.swap=Math.max(0,(this.swap||0)-dt);if(!this.active){this.time+=dt*.1;}else if(!this.modal){this.time+=dt;if(this.reloading){this.reloading.time-=dt;if(this.reloading.time<=0){const it=I.ITEMS[this.reloading.id];this.magazines[this.reloading.id]=Math.min(it.magazine,Math.floor((this.inventory[it.ammoItem||'ammo']||0)/(it.ammo||1)));this.reloading=null;this.sound('place');}}this.move(dt);const region=Math.floor(p.x/96)+','+Math.floor(p.z/96);if(!this.explored.includes(region)){this.explored.push(region);this.gainXP(55);this.notify('Новый край исследован: +55 опыта.');}if(this.input.attack)this.attack(dt);else if(this.input.mine)this.mine(dt);else this.mining=null;p.mana=Math.min(100,p.mana+dt*4);if(this.mode==='survival'){p.hunger=Math.max(0,p.hunger-dt*.10);if(p.hunger<=0)p.hp-=dt*.5;else if(p.hunger>75&&p.hp<100)p.hp=Math.min(100,p.hp+dt*.6);}else if(this.mode==='creative'){p.hp=100;p.mana=100;p.hunger=100;}
      const isClient=this.network&&this.network.role==='client';if(!isClient){this.updateEnemies(dt);this.updateHazards(dt);this.updateProjectiles(dt);if(this.mode!=='creative'&&this.enemies.filter(e=>!I.ENEMIES[e.type].boss).length<12){this.spawnTimer-=dt;if(this.spawnTimer<=0){const biome=this.world.biome(p.x,p.z),types=p.y<this.world.height(p.x,p.z)-3?['spider','shade','golem']:biome==='Пепельные земли'?['golem','wisp','shade']:biome==='Снежные высоты'?['icewolf','golem','skeleton']:biome==='Песчаный край'?['scarab','skeleton','wisp']:['slime','wolf','sprout','skeleton'];this.spawnEnemy(types[Math.floor(Math.random()*types.length)]);this.spawnTimer=10+Math.random()*12;}}}if(p.hp<=0)this.die();this.saveTimer+=dt;if(this.saveTimer>25){this.save(true);this.saveTimer=0;}if(this.network)this.network.update(dt);
    }
    for(let i=this.particles.length-1;i>=0;i--){const q=this.particles[i];q.life-=dt;q.x+=q.vx*dt;q.y+=q.vy*dt;q.z+=q.vz*dt;q.vy-=dt*5;if(q.life<=0)this.particles.splice(i,1);}
    this.streamTimer-=dt;if(this.streamTimer<=0){this.visible=this.world.loadAround(p.x,p.z,true);this.world.prune(p.x,p.z,this.renderer);this.streamTimer=.08;}
    if(this.renderer.stepMeshes)this.renderer.stepMeshes(this.world,this.visible,2.2);else{const c=this.world.dirty.shift();if(c?.dirty)this.renderer.mesh(this.world,c);}
    this.target=this.active&&!this.modal?this.world.ray(this.eye(),this.direction(),6):null;
  }
  move(dt){const p=this.player,k=this.input.keys;let ix=this.input.x+(k.KeyD||k.ArrowRight?1:0)-(k.KeyA||k.ArrowLeft?1:0),iz=this.input.z+(k.KeyW||k.ArrowUp?1:0)-(k.KeyS||k.ArrowDown?1:0);const len=Math.hypot(ix,iz);if(len>1){ix/=len;iz/=len;}p.moving=len>.1;p.slow=Math.max(0,(p.slow||0)-dt);const sprint=this.input.sprint||k.ShiftLeft,speed=(sprint&&p.hunger>10?6.9:4.4)*(p.slow>0?.5:1);const vx=(Math.cos(p.yaw)*ix+Math.sin(p.yaw)*iz)*speed,vz=(Math.sin(p.yaw)*ix-Math.cos(p.yaw)*iz)*speed;
    if(this.mode==='creative'&&p.flying){p.vy=0;const rise=(this.input.jump||k.Space?1:0)-(k.ControlLeft||this.input.descend?1:0);this.moveAxis('x',vx*dt);this.moveAxis('z',vz*dt);this.moveAxis('y',rise*speed*dt);p.y=I.clamp(p.y,1,85);}
    else{if((this.input.jump||k.Space)&&p.ground){p.vy=8.3;p.ground=false;this.sound('jump');}const water=this.world.get(p.x,p.y+.6,p.z)===5;p.vy-=dt*(water?8:23);if(water&&(this.input.jump||k.Space))p.vy=4;const dx=vx*dt*(water?.62:1),dz=vz*dt*(water?.62:1);this.moveAxis('x',dx);this.moveAxis('z',dz);const oldV=p.vy;if(!this.moveAxis('y',p.vy*dt)){if(oldV<0){p.ground=true;if(oldV<-12)this.damage(Math.floor((-oldV-12)*3));}p.vy=0;}else p.ground=false;}
    p.x=I.clamp(p.x,.5,767.5);p.z=I.clamp(p.z,.5,767.5);if(p.y<-5){p.y=80;p.vy=0;}if(sprint&&p.moving&&this.mode==='survival')p.hunger=Math.max(0,p.hunger-dt*.08);
  }
  moveAxis(axis,delta){if(!delta)return true;const p=this.player,steps=Math.max(1,Math.ceil(Math.abs(delta)/.15));let ok=true;for(let i=0;i<steps;i++){const n={x:p.x,y:p.y,z:p.z};n[axis]+=delta/steps;if(!this.world.collision(n.x,n.y,n.z)){p[axis]=n[axis];}else if(axis!=='y'&&p.ground&&!this.world.collision(n.x,n.y+.55,n.z)&&this.world.collision(n.x,n.y-.1,n.z)){p[axis]=n[axis];p.y+=.55;}else{ok=false;break;}}return ok;}
  aim(dx,dy,touch=false){if(this.modal||!this.active)return;const scale=touch?2.25/Math.max(240,Math.min(innerWidth,innerHeight)):.0025;this.player.yaw+=dx*scale*this.settings.sensitivity;this.player.pitch=I.clamp(this.player.pitch-dy*scale*this.settings.sensitivity*(this.settings.invert?-1:1),-1.45,1.45);}
  attack(dt){const id=this.selectedItem(),item=I.ITEMS[id];if(item.kind==='block'){if(this.cooldown<=0){this.place();this.cooldown=.22;}return;}if(item.kind==='summon'){if(this.cooldown<=0){this.summon(item.boss);this.cooldown=1;}return;}if(item.kind==='consumable'){if(this.cooldown<=0)this.consume(id);return;}if(item.kind==='tool'){const hit=this.findHit(this.eye(),this.direction(),item.range,.25);if(hit.enemy){this.hitMelee(item);this.mining=null;}else this.mine(dt);return;}if(item.kind==='melee'){this.hitMelee(item);return;}if(this.cooldown>0||this.reloading)return;this.fireWeapon(id);}
  hitMelee(item){if(this.cooldown>0)return false;this.cooldown=item.rate;this.swing=.28;this.swingTotal=.28;this.sound('swing');const hit=this.findHit(this.eye(),this.direction(),item.range,.35);if(!hit.enemy)return false;this.hurtEnemy(hit.enemy,item.damage);this.sound('hit');this.sendAction({type:'melee',id:hit.enemy.id,damage:item.damage});return true;}
  findHit(origin,dir,range,padding=.0){const block=this.world.ray(origin,dir,range);let best=block?block.t:range,enemy=null;for(const e of this.enemies){const d=I.ENEMIES[e.type],r=d.scale*.4+padding,height=d.scale*(e.type==='slime'?.65:d.animal||e.type==='wolf'?.9:1.77),min=[e.x-r,e.y-padding,e.z-r],max=[e.x+r,e.y+height+padding,e.z+r];let near=0,far=best,valid=true;for(let k=0;k<3;k++){if(Math.abs(dir[k])<1e-6){if(origin[k]<min[k]||origin[k]>max[k]){valid=false;break;}}else{let a=(min[k]-origin[k])/dir[k],b=(max[k]-origin[k])/dir[k];if(a>b)[a,b]=[b,a];near=Math.max(near,a);far=Math.min(far,b);if(near>far){valid=false;break;}}}if(valid&&near<=best){enemy=e;best=near;}}return {enemy,t:best,block:enemy?null:block};}
  fireWeapon(id,networked=false,remoteOrigin=null,remoteDir=null){const item=I.ITEMS[id];if(!item)return false;const creative=this.mode==='creative',isRemote=!!remoteOrigin,ammo=item.ammoItem||'ammo';if(!isRemote){if(this.reloading)return false;if(!creative&&item.ammo&&(this.inventory[ammo]||0)<item.ammo){this.notify('Нет боеприпасов. Создай их в рюкзаке.');this.cooldown=.7;return false;}if(!creative&&item.magazine){if(this.magazines[id]===undefined)this.magazines[id]=item.magazine;if(this.magazines[id]<=0){this.reload();return false;}}if(!creative&&item.mana&&this.player.mana<item.mana){this.notify('Недостаточно маны.');this.cooldown=.5;return false;}if(!creative&&item.ammo)this.inventory[ammo]-=item.ammo;if(!creative&&item.magazine)this.magazines[id]--;if(!creative&&item.mana)this.player.mana-=item.mana;this.cooldown=item.rate;this.flash=.07;this.actionChanged=true;this.sound(item.kind==='magic'?id:'shoot');}
    const origin=remoteOrigin||this.eye(),dir=remoteDir||this.direction();if(!networked)this.sendAction({type:'fire',weapon:id,origin,dir});const client=this.network&&this.network.role==='client'&&!networked;
    if(item.kind==='gun'){for(let i=0;i<(item.pellets||1);i++){const d=dir.map(v=>v+(Math.random()-.5)*item.spread*2),mag=Math.hypot(...d);for(let k=0;k<3;k++)d[k]/=mag;const hit=this.findHit(origin,d,item.range);if(hit.enemy){this.hitMarker=.15;if(!client)this.hurtEnemy(hit.enemy,item.damage);}const end=hit.t;for(let t=.5;t<Math.min(end,22);t+=.8)this.addParticle(origin[0]+d[0]*t,origin[1]+d[1]*t,origin[2]+d[2]*t,[1,.82,.42],.045,.08,true);if(hit.enemy||hit.block)this.burst(origin[0]+d[0]*end,origin[1]+d[1]*end,origin[2]+d[2]*end,hit.enemy?[.8,.35,.25]:[.75,.72,.58],7);}}
    else if(item.kind==='magic'&&!client)this.projectiles.push({x:origin[0]+dir[0]*.55,y:origin[1]+dir[1]*.55,z:origin[2]+dir[2]*.55,vx:dir[0]*item.speed,vy:dir[1]*item.speed,vz:dir[2]*item.speed,life:id==='grenade'?1.8:4,kind:id,damage:item.damage,burn:item.burn||0,freeze:item.freeze||0,blast:item.blast||0,gravity:item.gravity||0,friendly:true});return true;
  }
  spell(id){if(this.cooldown<=0&&!this.modal)this.fireWeapon(id);}
  mine(dt){if(!this.target)return;const t=this.target,b=I.BLOCKS[t.b];if(this.swing<=0){this.swing=.30;this.swingTotal=.30;}if(!Number.isFinite(b.hard)&&this.mode!=='creative'){this.mining=null;return;}const key=t.x+','+t.y+','+t.z;if(!this.mining||this.mining.key!==key)this.mining={key,progress:0};const tool=this.selectedItem(),factor=this.mode==='creative'?20:tool==='pick'?1.4:tool==='axe'&&(t.b===6||t.b===7)?2:.65;this.mining.progress+=dt*factor/(Number.isFinite(b.hard)?b.hard:1);if(Math.random()<dt*15)this.burst(t.x+.5,t.y+.5,t.z+.5,[.63,.61,.47],1);if(this.mining.progress>=1){const natural=!this.world.edits.has(key),tree=natural&&t.b===6?this.world.treeAt(t.x,t.y,t.z):null,removed=tree?this.world.fellTree(tree):[];if(removed.length||this.world.set(t.x,t.y,t.z,0)){const count=tree?removed.filter(q=>q.b===6).length:1;if(b.drop)this.inventory[b.drop]=(this.inventory[b.drop]||0)+count;if(natural)this.gainXP([8,12,22].includes(t.b)?8:t.b===6?count*2:1);for(const q of removed)this.sendAction({type:'block',x:q.x,y:q.y,z:q.z,b:0});this.burst(t.x+.5,t.y+.5,t.z+.5,[.65,.62,.5],12);this.sound('mine');this.sendAction({type:'block',x:t.x,y:t.y,z:t.z,b:0});if(this.ui)this.ui.inventoryDirty=true;}this.mining=null;}}
  place(){const id=this.selectedItem(),item=I.ITEMS[id];if(item.kind!=='block'){this.notify('Выбери блок на панели или в рюкзаке.');return false;}if(this.mode!=='creative'&&(this.inventory[id]||0)<1){this.notify('Этот материал закончился.');return false;}const t=this.target;if(!t||!t.previous)return false;const [x,y,z]=t.previous,p=this.player;if(x>=Math.floor(p.x-.3)&&x<=Math.floor(p.x+.3)&&z>=Math.floor(p.z-.3)&&z<=Math.floor(p.z+.3)&&y>=Math.floor(p.y)&&y<=Math.floor(p.y+1.78))return false;if(this.world.set(x,y,z,item.block)){if(this.mode!=='creative')this.inventory[id]--;this.sound('place');this.sendAction({type:'block',x,y,z,b:item.block});return true;}return false;}
  craft(index){const r=I.RECIPES[index];if(!r)return false;const requirement=this.recipeRequirement(r);if(requirement){this.notify(requirement);return false;}if(this.mode!=='creative')for(const [id,n] of Object.entries(r.cost))if((this.inventory[id]||0)<n){this.notify('Недостаточно ресурсов.');return false;}if(this.mode!=='creative')for(const [id,n] of Object.entries(r.cost))this.inventory[id]-=n;this.inventory[r.item]=(this.inventory[r.item]||0)+r.count;this.sound('craft');this.notify('Создано: '+I.ITEMS[r.item].name+' × '+r.count);if(this.ui)this.ui.inventoryDirty=true;return true;}
  consume(id){if((this.inventory[id]||0)<1){this.notify('Предмет закончился.');return;}if(id==='food'){this.player.hunger=Math.min(100,this.player.hunger+35);this.player.hp=Math.min(100,this.player.hp+5);}else if(id==='potion')this.player.hp=Math.min(100,this.player.hp+45);else return;if(this.mode!=='creative')this.inventory[id]--;this.cooldown=.7;this.sound('craft');this.notify(id==='food'?'Провизия съедена.':'Здоровье восстановлено.');}
  spawnEnemy(type,x=null,z=null){if(!I.ENEMIES[type])return null;const p=this.player;if(x===null){const angle=Math.random()*Math.PI*2,r=19+Math.random()*16;x=I.clamp(p.x+Math.sin(angle)*r,2,766);z=I.clamp(p.z+Math.cos(angle)*r,2,766);}const def=I.ENEMIES[type],e={id:this.nextId++,type,x,y:this.world.surface(x,z,true)+.01,z,yaw:Math.atan2(p.x-x,-(p.z-z)),hp:def.health,attack:1+Math.random(),hit:0,burn:0,freeze:0,phase:0};this.enemies.push(e);return e;}
  summon(type){if(this.network&&this.network.role==='client'){this.sendAction({type:'summon',boss:type});this.notify('Запрос отправлен хозяину. Призыв расходует его реликвию.');return false;}const d=I.ENEMIES[type];if(!d?.boss)return false;if(this.enemies.some(e=>I.ENEMIES[e.type].boss)){this.notify('Сначала победи текущего босса.');return false;}const requirement=this.bossRequirement(type);if(requirement){this.notify(requirement);return false;}const dir=this.direction(),x=I.clamp(this.player.x+dir[0]*15,4,764),z=I.clamp(this.player.z+dir[2]*15,4,764);this.spawnEnemy(type,x,z);if(this.mode==='survival')this.inventory[d.relic]--;this.notify(d.name+' пробуждается!');this.sound('boss');if(this.ui)this.ui.closeModal();return true;}
  updateEnemies(dt){const p=this.player;for(let i=this.enemies.length-1;i>=0;i--){const e=this.enemies[i],d=I.ENEMIES[e.type];e.hit=Math.max(0,e.hit-dt);e.freeze=Math.max(0,e.freeze-dt);if(e.burn>0){e.burn-=dt;e.hp-=dt*8;if(Math.random()<dt*10)this.addParticle(e.x,e.y+d.scale,e.z,[1,.44,.12],.12,.6,true);}if(e.hp<=0){this.killEnemy(i);continue;}let victim=p;for(const rp of Object.values(this.remotePlayers))if(Math.hypot(rp.x-e.x,rp.z-e.z)<Math.hypot(victim.x-e.x,victim.z-e.z))victim=rp;const dx=victim.x-e.x,dz=victim.z-e.z,dist=Math.hypot(dx,dz);e.yaw=Math.atan2(dx,-dz);if(dist>100&&!d.boss){this.enemies.splice(i,1);continue;}const awake=this.mode!=='creative'&&dist<45;if(awake){const stop=d.ranged?8:d.scale*.6+.9;if(dist>stop){const speed=d.speed*(e.charge>0?3.2:1)*(e.freeze>0?.20:1)*(d.boss&&e.hp<d.health*.5?1.25:1),nx=e.x+dx/dist*speed*dt,nz=e.z+dz/dist*speed*dt,h=this.world.height(nx,nz)+1;if(h-e.y<1.4&&!this.world.collision(nx,e.y+.15,nz,d.scale*.21,d.scale*1.7)){e.x=nx;e.z=nz;}else if(!this.world.collision(nx,e.y+1.05,nz,d.scale*.21,d.scale*1.7)){e.y+=Math.min(1.2,dt*5);e.x=nx;e.z=nz;}}
      const ground=this.world.surface(e.x,e.z,true);if(e.y>ground)e.y=Math.max(ground,e.y-dt*9);else if(e.y<ground)e.y=Math.min(ground,e.y+dt*3);e.charge=Math.max(0,(e.charge||0)-dt);e.attack-=dt;if(e.attack<=0){e.attack=d.boss?2.2:1.5;if(d.ranged&&dist<34){const origin=[e.x,e.y+d.scale*1.2,e.z],target=[victim.x,victim.y+1,victim.z],diff=target.map((v,k)=>v-origin[k]),n=Math.hypot(...diff);const kind=e.type==='frostking'?'frost':e.type==='stormlord'?'storm':e.type==='abyss'||e.type==='shade'?'void':e.type==='skeleton'?'crossbow':'fire';this.projectiles.push({x:origin[0],y:origin[1],z:origin[2],vx:diff[0]/n*12,vy:diff[1]/n*12,vz:diff[2]/n*12,life:4,kind,damage:d.damage,freeze:kind==='frost'?2:0,friendly:false});e.attack=d.boss?1.6:2.5;}else if(dist<d.scale*.65+1.1){if(victim===p)this.damage(d.damage);else this.sendAction({type:'remoteDamage',player:victim.id,damage:d.damage});e.attack=d.boss?1.2:1.5;}
        if(d.boss){e.phase++;if(e.type==='root'&&e.phase%3===0){this.bossPulse(e,7,12,'root');if(this.enemies.length<20)for(let k=0;k<2;k++)this.spawnEnemy('sprout',e.x+(k?3:-3),e.z+3);}if(e.type==='titan'&&e.phase%3===0)this.bossPulse(e,6,18,'fire');if(e.type==='frostking'&&e.phase%4===0){this.bossPulse(e,9,12,'frost');}if(e.type==='stormlord'&&e.phase%2===0)this.radialVolley(e,'storm',10,14);if(e.type==='scarabking'&&e.phase%3===0){if(this.enemies.length<20)this.spawnEnemy('scarab',e.x+4,e.z);e.charge=1.2;this.bossPulse(e,7,15,'sand');}if(e.type==='abyss'&&e.phase%4===0){if(this.enemies.length<20)this.spawnEnemy('shade',e.x-5,e.z+3);this.radialVolley(e,'void',8,16);this.bossPulse(e,10,16,'void');}if(e.type==='sentinel'&&e.phase%2===0){this.radialVolley(e,e.phase%4?'fire':'frost',12,18);this.bossPulse(e,8,18,e.phase%4?'fire':'frost');}}}
    }}
  }
  bossPulse(e,radius,damage,kind='fire'){this.hazards.push({x:e.x,y:this.world.surface(e.x,e.z,true)+.04,z:e.z,radius,damage,kind,time:1.15,total:1.15});}
  updateHazards(dt){for(let i=this.hazards.length-1;i>=0;i--){const q=this.hazards[i];q.time-=dt;if(q.kind==='void'&&Math.hypot(q.x-this.player.x,q.z-this.player.z)<q.radius){const d=Math.max(1,Math.hypot(q.x-this.player.x,q.z-this.player.z));this.moveAxis('x',(q.x-this.player.x)/d*dt*1.8);this.moveAxis('z',(q.z-this.player.z)/d*dt*1.8);}if(q.time<=0){const color=q.kind==='frost'?[.3,.8,1]:q.kind==='void'?[.75,.25,.82]:q.kind==='root'?[.3,.85,.4]:[1,.38,.12];this.burst(q.x,q.y+.5,q.z,color,40,true);const hit=p=>Math.hypot(q.x-p.x,q.z-p.z)<q.radius&&Math.abs(p.y-q.y)<4;if(hit(this.player)){this.damage(q.damage);if(q.kind==='frost'||q.kind==='root')this.player.slow=3;}for(const p of Object.values(this.remotePlayers))if(hit(p))this.sendAction({type:'remoteDamage',player:p.id,damage:q.damage});this.hazards.splice(i,1);}}}
  radialVolley(e,kind,count,damage){for(let i=0;i<count;i++){const a=i/count*Math.PI*2;this.projectiles.push({x:e.x,y:e.y+1.4,z:e.z,vx:Math.sin(a)*14,vy:0,vz:Math.cos(a)*14,life:3,kind,damage,freeze:kind==='frost'?2:0,friendly:false});}}
  hurtEnemy(e,damage,burn=0,freeze=0){if(!e)return;if(this.network&&this.network.role==='client')return;this.hitMarker=.15;e.hp-=damage;e.hit=.16;e.burn=Math.max(e.burn,burn);e.freeze=Math.max(e.freeze,freeze);this.burst(e.x,e.y+I.ENEMIES[e.type].scale,e.z,freeze?[.4,.8,1]:burn?[1,.45,.1]:[.8,.4,.3],6,true);}
  killEnemy(index){const e=this.enemies[index],d=I.ENEMIES[e.type];this.enemies.splice(index,1);this.kills++;for(const [id,n] of Object.entries(d.loot))this.inventory[id]=(this.inventory[id]||0)+n;this.gainXP(d.xp||20);this.burst(e.x,e.y+1,e.z,d.color,22);if(d.boss){if(!this.bosses.includes(e.type))this.bosses.push(e.type);this.notify('Победа! '+d.name+'. Добыта древняя эссенция для следующей реликвии.');this.sound('craft');}else this.notify(d.name+': +'+(d.xp||20)+' опыта, добыча собрана.');if(this.ui)this.ui.inventoryDirty=true;}
  updateProjectiles(dt){for(let i=this.projectiles.length-1;i>=0;i--){const q=this.projectiles[i];q.life-=dt;q.vy-=(q.gravity||0)*dt;const steps=Math.ceil(Math.hypot(q.vx,q.vy,q.vz)*dt/.16);let remove=q.life<=0;for(let s=0;s<steps&&!remove;s++){q.x+=q.vx*dt/steps;q.y+=q.vy*dt/steps;q.z+=q.vz*dt/steps;if(this.world.solid(q.x,q.y,q.z)){remove=true;break;}if(q.friendly){for(const e of this.enemies){const d=I.ENEMIES[e.type];if(Math.hypot(e.x-q.x,e.y+d.scale*.85-q.y,e.z-q.z)<d.scale*.65+.2){this.hurtEnemy(e,q.damage,q.burn,q.freeze);remove=true;break;}}}else{if(Math.hypot(q.x-this.player.x,q.y-(this.player.y+1),q.z-this.player.z)<.75){this.damage(q.damage);if(q.freeze)this.player.slow=q.freeze;remove=true;}for(const p of Object.values(this.remotePlayers))if(Math.hypot(q.x-p.x,q.y-(p.y+1),q.z-p.z)<.75){this.sendAction({type:'remoteDamage',player:p.id,damage:q.damage});remove=true;}}}
      const color=q.kind==='frost'?[.40,.82,1]:q.kind==='storm'?[.70,.60,1]:q.kind==='void'?[.82,.28,.75]:[1,.43,.10];if(!['bow','crossbow','grenade'].includes(q.kind)&&Math.random()<.5)this.addParticle(q.x,q.y,q.z,color,.12,.3,true);if(remove){this.burst(q.x,q.y,q.z,color,q.blast?40:10,true);if(q.blast&&q.friendly)for(const e of this.enemies){const distance=Math.hypot(e.x-q.x,e.y+1-q.y,e.z-q.z);if(distance<q.blast)this.hurtEnemy(e,q.damage*(1-distance/q.blast));}this.projectiles.splice(i,1);}}
  }
  damage(n){if(this.mode==='creative')return;this.player.hp=Math.max(0,this.player.hp-n);if(this.ui)this.ui.damageFlash();this.sound('hurt');}
  die(){if(this.network&&this.network.role==='client'){this.player.hp=100;this.player.x=384.5;this.player.y=18.05;this.player.z=384.5;this.notify('Ты возродился у лагеря.');return;}this.save(true);this.active=false;this.modal=true;this.input.attack=false;this.input.mine=false;if(this.ui)this.ui.showDeath();}
  respawn(){this.player.hp=100;this.player.mana=100;this.player.hunger=70;this.player.x=384.5;this.player.y=18.05;this.player.z=384.5;this.player.vy=0;this.active=true;this.modal=false;if(this.ui)this.ui.showGame();this.notify('Ты вернулся в лагерь. Постройки и рюкзак сохранены.');}
  addParticle(x,y,z,color,size=.1,life=.5,glow=false){if(this.particles.length>=(this.settings.quality==='low'?48:96))return;this.particles.push({x,y,z,color,size,life,max:life,vx:(Math.random()-.5)*2.5,vy:Math.random()*2,vz:(Math.random()-.5)*2.5,glow});}
  burst(x,y,z,color,count=10,glow=false){for(let i=0;i<count;i++)this.addParticle(x,y,z,color,.06+Math.random()*.10,.3+Math.random()*.4,glow);}
  notify(text){if(this.ui)this.ui.toast(text);else this.events.push(text);}
  sendAction(action){if(this.network)this.network.action(action);}
  sound(kind){if(!this.settings.sound)return;try{if(!this.audio)this.audio=new (window.AudioContext||window.webkitAudioContext)();if(this.audio.state==='suspended')this.audio.resume();const c=this.audio,o=c.createOscillator(),gain=c.createGain(),now=c.currentTime;const freq={shoot:120,fire:270,frost:700,mine:170,place:240,hit:90,hurt:70,craft:620,start:480,jump:220,boss:55,swing:180}[kind]||300;o.type=kind==='shoot'||kind==='mine'?'sawtooth':'sine';o.frequency.setValueAtTime(freq,now);o.frequency.exponentialRampToValueAtTime(Math.max(30,freq*.38),now+.12);gain.gain.setValueAtTime(kind==='boss'?.12:.05,now);gain.gain.exponentialRampToValueAtTime(.001,now+.14);o.connect(gain);gain.connect(c.destination);o.start();o.stop(now+.15);}catch(e){}}
}
I.Game=Game;
})(ISKRA);
