'use strict';
(function(I){
const paths={
  bow:'M2 3c8 2 8 16 0 18M2 3l6 9-6 9M8 12h14M18 9l4 3-4 3',
  pick:'M5 20 16 9M8 5c5-2 10-1 13 4l-3 2c-3-3-6-4-10-3L8 5Z',
  axe:'M6 21 16 5M12 4l5-2 5 6-5 5-5-9Z',
  sword:'M4 21 8 17M6 14l5 5M8 16 18 3l3-1-1 4L10 18',
  pistol:'M3 8h17v5H10l-1 8H5l1-8H3V8ZM14 13v4h-4M20 9h2',
  rifle:'M2 8h17v5h-7l-1 5H8l-1-5H2V8ZM19 10h4M15 13v6h-3M5 8V6h7',
  shotgun:'M2 9h16v4H8l-2 6H3l2-6H2V9ZM18 10h5M18 12h5M11 13v3',
  fire:'M13 2c2 7 7 8 7 13a8 8 0 0 1-16 0c0-3 2-6 5-8-1 4 1 6 3 6 2-3 2-6 1-11ZM12 14c-3 3-4 6 0 7 4-1 3-4 0-7Z',
  frost:'M12 2v20M3 7l18 10M3 17 21 7M8 4l4 3 4-3M8 20l4-3 4 3M3 11l4-1-1-4M21 13l-4 1 1 4M6 18l1-4-4-1M18 6l-1 4 4 1',
  block:'M12 2 22 7v11l-10 5-10-5V7l10-5ZM2 7l10 5 10-5M12 12v11',
  ore:'M3 16 7 6l11-2 4 13-8 5-11-6ZM7 6l7 7 4-9M3 16l11-3v9M14 13l8 4',
  crystal:'M12 2 19 9l-2 10-5 4-5-4L5 9l7-7ZM12 2v21M5 9l7 3 7-3',
  ammo:'M5 22V8l3-6 3 6v14H5ZM14 22V8l3-6 3 6v14h-6ZM5 17h6M14 17h6',
  food:'M8 4c-5 1-6 6-4 11 2 4 5 7 8 5 3 2 6-1 8-5 2-5 1-10-4-11-2 0-3 1-4 1s-2-1-4-1ZM12 5V2M12 4c1-3 4-3 6-3',
  potion:'M9 2h6v6l5 8c2 4-1 6-4 6H8c-3 0-6-2-4-6l5-8V2ZM9 5h6M6 15h12M12 14v5M10 17h4',
  heart:'M12 21 3 12C-3 4 7-1 12 6 17-1 27 4 21 12l-9 9Z',
  bag:'M6 6h12l3 5v10H3V11l3-5ZM8 6V3h8v3M6 13h12v5H6v-5ZM8 11V9M16 11V9',
  pause:'M8 4v16M16 4v16',
  jump:'M12 21V3M5 10l7-7 7 7M5 21h14',
  aim:'M12 2v5M12 17v5M2 12h5M17 12h5M5 5l3 3M19 5l-3 3M5 19l3-3M19 19l-3-3M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8',
  boss:'M5 6 3 2l6 4h6l6-4-2 4v9l-7 7-7-7V6ZM8 11h2M14 11h2M9 16h6'
};
function icon(name){return '<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="'+(paths[name]||paths.block)+'"/></svg>';}
const $=id=>document.getElementById(id),esc=I.escape;
class UI{
  constructor(game){this.g=game;game.ui=this;this.mode='survival';this.modalType='';this.tab='inventory';this.filter='all';this.inventoryDirty=true;this.toastTimer=0;this.hotbarCache='';this.lastJump=0;this.editingControls=false;this.bind();this.decorate();this.loadMods();this.applyControls();this.bindEditor();setTimeout(()=>{$('boot').classList.add('hidden');$('menu').classList.remove('hidden');this.updateContinue();},450);}
  decorate(root=document){root.querySelectorAll('[data-icon]').forEach(e=>{const small=e.querySelector('small');e.innerHTML=icon(e.dataset.icon)+(small?small.outerHTML:'');});}
  bind(){document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{this.mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));this.updateContinue();});$('start').onclick=()=>this.g.start(this.mode);$('continue').onclick=()=>this.g.start(this.mode,true);$('menu-settings').onclick=()=>this.showSettings();$('menu-help').onclick=()=>this.showHelp();$('menu-mods').onclick=()=>this.showMods();$('modal-close').onclick=()=>this.closeModal();$('bag').onclick=()=>this.showBag();$('pause').onclick=()=>this.showPause();this.controls=new I.TouchControls(this.g);
    document.addEventListener('mousemove',e=>{if(document.pointerLockElement===$('world'))this.g.aim(e.movementX,e.movementY);});document.addEventListener('mouseup',e=>{if(document.pointerLockElement===$('world')&&!(e.sourceCapabilities?.firesTouchEvents)){this.g.input.attack=false;this.g.input.mine=false;}});$('world').addEventListener('contextmenu',e=>e.preventDefault());
    document.addEventListener('keydown',e=>{if(e.target.tagName==='INPUT'||e.target.tagName==='SELECT')return;if(['Space','Tab','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Escape'){if(this.g.modal)this.closeModal();else if(this.g.active)this.showPause();return;}if(!this.g.active||this.g.modal)return;this.g.input.keys[e.code]=true;if(e.repeat)return;if(/^Digit[1-8]$/.test(e.code))this.selectSlot(+e.code.slice(-1)-1);if(e.code==='KeyR')this.g.reload();if(e.code==='KeyQ')this.g.spell('fire');if(e.code==='KeyE')this.g.spell('frost');if(e.code==='KeyB'||e.code==='Tab')this.showBag();if(e.code==='KeyF')this.g.consume('food');if(e.code==='KeyH')this.g.consume('potion');if(e.code==='Space'&&this.g.mode==='creative'){const now=performance.now();if(now-this.lastJump<320)this.g.player.flying=!this.g.player.flying;this.lastJump=now;}});document.addEventListener('keyup',e=>delete this.g.input.keys[e.code]);document.addEventListener('visibilitychange',()=>{if(document.hidden){this.resetInput();this.g.save(true);if(this.g.active&&!this.g.modal)this.showPause();}});window.addEventListener('blur',()=>this.resetInput());window.addEventListener('pagehide',()=>this.g.save(true));window.addEventListener('resize',()=>{this.resetInput();this.g.renderer.resize();});$('mod-file').onchange=async e=>{const file=e.target.files[0];if(file){if(file.size>150000){this.toast('Мод должен быть меньше 150 КБ.');return;}this.importMod(await file.text());}e.target.value='';};
  }
  resetInput(){this.controls?.reset();Object.assign(this.g.input,{x:0,z:0,jump:false,attack:false,mine:false,descend:false,keys:{}});$('joy-knob').style.transform='';}
  updateContinue(){$('continue').classList.toggle('hidden',!localStorage.getItem('iskra.save.'+this.mode));}
  selectSlot(i){this.g.selectSlot(i);this.hotbarCache='';this.g.sound('place');}
  showGame(){this.closeModal();$('menu').classList.add('hidden');$('hud').classList.remove('hidden');$('boot').classList.add('hidden');this.hotbarCache='';this.update();}
  open(title,type,eyebrow='ДИКИЙ РУБЕЖ'){this.modalType=type;this.g.modal=true;this.resetInput();if(document.pointerLockElement)document.exitPointerLock();$('modal-title').textContent=title;$('modal-eyebrow').textContent=eyebrow;$('modal').classList.remove('hidden');}
  closeModal(){$('modal').classList.add('hidden');this.modalType='';this.g.modal=!this.g.active;this.resetInput();}
  update(){const g=this.g,p=g.player;for(const [id,val] of [['hp',p.hp],['mana',p.mana],['hunger',p.hunger]]){$(id+'-value').textContent=Math.ceil(val);$(id+'-bar').style.width=I.clamp(val,0,100)+'%';}$('mode-label').textContent={survival:'ВЫЖИВАНИЕ',creative:'ТВОРЧЕСТВО',hunt:'ОХОТА'}[g.mode];$('biome').textContent=g.world.biome(p.x,p.z);$('coords').textContent=`${Math.floor(p.x)} / ${Math.floor(p.y)} / ${Math.floor(p.z)} · ${g.time%900<450?'ДЕНЬ':'НОЧЬ'}`;
    $('progress-hud').classList.toggle('hidden',g.mode!=='survival');$('level-label').textContent='УРОВЕНЬ '+g.level;$('xp-label').textContent=g.xp+' / '+g.xpNeeded();$('xp-bar').style.width=(g.xp/g.xpNeeded()*100)+'%';
    const id=g.selectedItem(),item=I.ITEMS[id],pool=item.ammoItem||'ammo',mag=g.magazines[id]??item.magazine;let ammoText=item.ammo?' · '+(g.mode==='creative'?'∞':item.magazine?mag+'/'+item.magazine+' · запас '+(g.inventory[pool]||0):g.inventory[pool]||0):'';
    $('item-label').textContent=item.name+(g.reloading?' · перезарядка '+g.reloading.time.toFixed(1)+' с':ammoText);const action=g.actionInfo();if(this.actionCache!==action.label+action.icon){this.actionCache=action.label+action.icon;$('attack').innerHTML=icon(action.icon)+'<small>'+action.label+'</small>';$('attack').setAttribute('aria-label',action.label);}$('attack').classList.toggle('loading',!!g.reloading);$('jump').setAttribute('aria-label',p.flying?'Вверх / вниз':'Прыжок');$('target-label').textContent=g.target?I.BLOCKS[g.target.b].name:'';$('mining-ring').classList.toggle('hidden',!g.mining);if(g.mining)$('mining-circle').style.strokeDashoffset=126*(1-I.clamp(g.mining.progress,0,1));const boss=g.enemies.find(e=>I.ENEMIES[e.type].boss);$('boss-hud').classList.toggle('hidden',!boss);if(boss){const d=I.ENEMIES[boss.type];$('boss-name').textContent=d.name;$('boss-bar').style.width=Math.max(0,boss.hp/d.health*100)+'%';$('boss-health').textContent=Math.ceil(boss.hp)+' / '+d.health;}
    const cache=JSON.stringify([g.hotbar,g.slot,g.hotbar.map(id=>g.inventory[id]),g.mode]);if(cache!==this.hotbarCache){this.hotbarCache=cache;$('hotbar').innerHTML=g.hotbar.map((id,i)=>{const it=I.ITEMS[id],n=g.inventory[id]||0;return `<button class="slot ${i===g.slot?'selected':''} ${!n?'empty':''}" data-slot="${i}" title="${esc(it.name)}" style="color:${i===g.slot?'var(--gold)':it.color}">${I.itemArt(id)}<small>${it.kind==='block'?(g.mode==='creative'?'∞':n):''}</small><span class="key">${i+1}</span></button>`;}).join('');$('hotbar').querySelectorAll('button').forEach(b=>b.onclick=()=>this.selectSlot(+b.dataset.slot));}
    $('hit-marker').classList.toggle('hit',g.hitMarker>0);$('performance').classList.toggle('hidden',!g.settings.showFps);$('performance').textContent=`${Math.round(g.fps)} FPS · ${g.renderer.canvas.width}×${g.renderer.canvas.height} · ${g.renderer.drawCalls} выз. · ${Math.round(g.frameMS||0)} мс`;if(this.inventoryDirty&&this.modalType==='bag'){this.renderBag(true);this.inventoryDirty=false;}this.updateNetwork();
  }
  toast(text){clearTimeout(this.toastTimer);$('toast').textContent=text;$('toast').classList.add('visible');this.toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3200);}
  damageFlash(){$('damage').classList.add('hit');setTimeout(()=>$('damage').classList.remove('hit'),160);}
  bindBagGestures(){const content=$('modal-content');content.onpointerdown=e=>{this.bagDragged=false;this.bagStart={x:e.clientX,y:e.clientY};};content.onpointermove=e=>{if(this.bagStart&&Math.hypot(e.clientX-this.bagStart.x,e.clientY-this.bagStart.y)>9)this.bagDragged=true;};content.onpointercancel=()=>{this.bagDragged=true;};if(!this.bagCaptureBound){content.addEventListener('click',e=>{if(this.bagDragged){e.stopImmediatePropagation();e.preventDefault();}},true);this.bagCaptureBound=true;}}
  showBag(){this.open('Рюкзак и мастерская','bag','СОБИРАЙ · СОЗДАВАЙ · УЛУЧШАЙ');this.renderBag();}
  renderBag(preserve=false){const oldScroll=preserve?$('modal-content').scrollTop:0;const g=this.g,tabs=`<div class="tabs"><button data-tab="inventory" class="${this.tab==='inventory'?'active':''}">Предметы</button><button data-tab="craft" class="${this.tab==='craft'?'active':''}">Создание</button><button data-tab="bosses" class="${this.tab==='bosses'?'active':''}">Боссы</button></div>`;let html='';
    if(this.tab==='inventory'){html='<div class="inventory-filter">'+[['all','Всё'],['weapons','Оружие'],['tool','Инструменты'],['block','Блоки'],['supplies','Запасы']].map(([id,label])=>`<button data-filter="${id}" class="${this.filter===id?'active':''}">${label}</button>`).join('')+'</div><p>Нажми на предмет, чтобы поставить его в выбранную ячейку панели. Еда и зелья используются сразу.</p><div class="inventory-grid">'+Object.entries(I.ITEMS).filter(([id,it])=>(g.inventory[id]||0)>0&&(this.filter==='all'||this.filter==='weapons'&&['gun','magic','melee'].includes(it.kind)||this.filter===it.kind||this.filter==='supplies'&&['resource','consumable','summon'].includes(it.kind))).map(([id,it])=>`<button class="inventory-item ${g.selectedItem()===id?'active':''}" data-item="${id}"><span style="color:${it.color}">${I.itemArt(id)}</span><b>${esc(it.name)}</b><small>${g.mode==='creative'?'∞':g.inventory[id]}</small></button>`).join('')+'</div>';}
    if(this.tab==='craft')html=I.RECIPES.map((r,index)=>{const it=I.ITEMS[r.item],lock=g.recipeRequirement(r),can=!lock&&(g.mode==='creative'||Object.entries(r.cost).every(([id,n])=>(g.inventory[id]||0)>=n));return `<div class="recipe ${lock?'locked':''}"><span style="color:${it.color}">${I.itemArt(r.item)}</span><div><b>${esc(it.name)} × ${r.count}</b><small>${Object.entries(r.cost).map(([id,n])=>esc(I.ITEMS[id].name)+' '+(g.inventory[id]||0)+'/'+n).join(' · ')}</small>${lock?'<small class="requirement">'+esc(lock)+'</small>':''}</div><button data-craft="${index}" ${can?'':'disabled'}>Создать</button></div>`;}).join('');
    if(this.tab==='bosses')html=`<div class="progress-card">${g.mode==='survival'?'Уровень '+g.level+' · '+g.xp+'/'+g.xpNeeded()+' опыта. Побеждай существ, добывай руду и открывай новые области.':'Свободные бои: все боссы доступны без реликвий.'}</div><p>Для призыва в выживании создай личную реликвию босса. Следующий открывается после нужного уровня и предыдущей победы. Реликвия расходуется при успешном призыве.</p>`+I.BOSS_IDS.map(id=>{const d=I.ENEMIES[id],lock=g.bossRequirement(id),gate=g.bossRequirement(id,false),recipe=I.RECIPES.findIndex(r=>r.item===d.relic),r=I.RECIPES[recipe],canCraft=!gate&&Object.entries(r.cost).every(([k,n])=>(g.inventory[k]||0)>=n),needItem=g.mode==='survival'&&!(g.inventory[d.relic]>0);return `<div class="boss-card ${lock?'locked':''}"><span>${icon('boss')}</span><div><b>${esc(d.name)} ${g.bosses.includes(id)?'✓':''}</b><small>Уровень ${d.level} · ${d.health} здоровья<br>${esc(I.BOSS_INFO[id])}<br>Реликвия: ${esc(I.ITEMS[d.relic].name)} · ${g.inventory[d.relic]||0} шт.</small>${lock?'<small class="requirement">'+esc(lock)+'</small>':''}</div>${needItem?`<button data-relic="${recipe}" ${canCraft?'':'disabled'}>Создать реликвию</button>`:`<button data-boss="${id}" ${lock?'disabled':''}>Призвать</button>`}</div>`;}).join('');
    $('modal-content').innerHTML=tabs+html;$('modal-content').scrollTop=oldScroll;this.bindBagGestures();document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{this.filter=b.dataset.filter;this.renderBag();});document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{this.tab=b.dataset.tab;this.renderBag();});document.querySelectorAll('[data-item]').forEach(b=>b.onclick=e=>{if(this.bagDragged){e.preventDefault();return;}const id=b.dataset.item,it=I.ITEMS[id];if(it.kind==='resource'){this.toast('Этот ресурс используется в создании предметов.');return;}if(it.kind==='consumable'){g.consume(id);this.renderBag(true);return;}g.hotbar[g.slot]=id;g.selectSlot(g.slot);this.hotbarCache='';this.closeModal();this.update();});document.querySelectorAll('[data-craft]').forEach(b=>b.onclick=()=>{g.craft(+b.dataset.craft);this.renderBag(true);});document.querySelectorAll('[data-relic]').forEach(b=>b.onclick=()=>{g.craft(+b.dataset.relic);this.renderBag(true);});document.querySelectorAll('[data-boss]').forEach(b=>b.onclick=()=>g.summon(b.dataset.boss));
  }
  showPause(){this.open('Передышка','pause','МИР ПОДОЖДЁТ');$('modal-content').innerHTML='<div class="pause-grid"><button id="resume-game">Вернуться в мир<span>Продолжить приключение</span></button><button id="save-game">Сохранить<span>Постройки, ресурсы и персонаж</span></button><button id="pause-friends">Играть с друзьями<span>До 4 игроков по Wi-Fi</span></button><button id="pause-settings">Настройки<span>Графика, управление и звук</span></button><button id="pause-help">Как играть<span>Управление и подсказки</span></button><button id="exit-menu">Главное меню<span>Сохранить и выйти</span></button></div>';$('resume-game').onclick=()=>this.closeModal();$('save-game').onclick=()=>this.g.save();$('pause-friends').onclick=()=>this.showFriends();$('pause-settings').onclick=()=>this.showSettings();$('pause-help').onclick=()=>this.showHelp();$('exit-menu').onclick=()=>{this.g.save(true);this.g.network.stop();this.g.active=false;this.closeModal();$('hud').classList.add('hidden');$('menu').classList.remove('hidden');this.updateContinue();};}
  showSettings(){this.open('Настройки','settings','ГРАФИКА · УПРАВЛЕНИЕ · ЗВУК');const s=this.g.settings;
    const select=(id,label,options,note='')=>`<div class="setting-row"><label>${label}${note?'<small>'+note+'</small>':''}</label><select id="${id}">${options.map(([v,t])=>`<option value="${v}" ${String(s[id])===String(v)?'selected':''}>${t}</option>`).join('')}</select></div>`;
    const slider=(id,label,min,max,step,note='')=>`<div class="setting-row"><label>${label}${note?'<small>'+note+'</small>':''}</label><input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${s[id]}"></div>`;
    const check=(id,label)=>`<div class="setting-row"><label>${label}</label><input id="${id}" type="checkbox" ${s[id]?'checked':''}></div>`;
    $('modal-content').innerHTML=select('quality','Дальность отрисовки',[['low','Экономичная · 2 участка'],['balanced','Сбалансированная · 3 участка'],['high','Высокая · 4 участка']])+select('resolution','Разрешение мира',[['auto','Автоматически'],['360','360p · экономичное'],['540','540p'],['720','720p · HD'],['1080','1080p · Full HD']],'Пропорции экрана сохраняются; меню остаётся чётким')+select('fps','Ограничение кадров',[[30,'30 FPS'],[45,'45 FPS'],[60,'60 FPS']])+slider('fov','Угол обзора',60,95,1)+slider('sensitivity','Чувствительность камеры',.25,2.5,.05)+select('stickMode','Центр джойстика',[['fixed','Фиксированный'],['floating','Под пальцем']])+slider('deadzone','Зона нечувствительности',0,.22,.01)+check('autoSprint','Бег при полном наклоне вперёд')+check('adaptive','Автоматически подбирать разрешение')+slider('joystickSize','Размер джойстика',.65,1.6,.05)+slider('buttonSize','Размер кнопок',.65,1.6,.05)+slider('hudSize','Размер панели и интерфейса',.7,1.4,.05)+slider('opacity','Прозрачность управления',.3,1,.05)+check('leftHand','Джойстик справа')+check('invert','Инверсия камеры по вертикали')+check('sound','Звук')+check('showFps','Показывать FPS и разрешение')+`<button id="edit-controls" class="primary">ИЗМЕНИТЬ ПОЛОЖЕНИЕ КНОПОК <span>↗</span></button><button id="reset-controls" class="subtle">Сбросить управление</button><p class="notice">Игра использует весь экран. На слабом телефоне начни с 360p, экономичной дальности и 30 FPS. Минимум — Android 7.0+ с поддержкой WebGL. Системное разрешение телефона не меняется.</p>`;
    for(const id of ['quality','resolution','fps','fov','sensitivity','stickMode','deadzone','autoSprint','adaptive','joystickSize','buttonSize','hudSize','opacity','leftHand','invert','sound','showFps'])$(id).onchange=()=>{const e=$(id),value=e.type==='checkbox'?e.checked:e.type==='range'||id==='fps'?+e.value:e.value;this.g.setSettings({[id]:value});};$('edit-controls').onclick=()=>this.editControls();$('reset-controls').onclick=()=>{this.g.setSettings({joystickSize:1,buttonSize:1,hudSize:1,opacity:.82,leftHand:false,stickMode:'fixed',deadzone:.06,sensitivity:1,autoSprint:true,layout:{}});this.showSettings();};
  }
  applyControls(){const s=this.g.settings,root=document.documentElement;root.style.setProperty('--joy-scale',s.joystickSize||1);root.style.setProperty('--button-scale',s.buttonSize||1);root.style.setProperty('--hud-scale',s.hudSize||1);root.style.setProperty('--controls-opacity',s.opacity||.85);document.body.classList.toggle('left-handed',!!s.leftHand);for(const id of ['joystick','jump','attack','hotbar']){const e=$(id),p=s.layout?.[id];for(const k of ['left','top','right','bottom','transform'])e.style[k]='';if(p&&Number.isFinite(p.x)&&Number.isFinite(p.y)){e.style.left=I.clamp(p.x,4,96)+'%';e.style.top=I.clamp(p.y,5,95)+'%';e.style.right='auto';e.style.bottom='auto';const scale=id==='joystick'?'var(--joy-scale)':id==='hotbar'?'var(--hud-scale)':id==='sprint'?'1':'var(--button-scale)';e.style.transform=`translate(-50%,-50%) scale(${scale})`;}}}
  editControls(){this.closeModal();this.g.modal=true;this.editingControls=true;$('menu').classList.add('hidden');$('hud').classList.remove('hidden');$('control-editor').classList.remove('hidden');document.body.classList.add('editing-controls');}
  bindEditor(){let moving=null,offsetX=0,offsetY=0;document.addEventListener('pointerdown',e=>{if(!this.editingControls)return;const el=e.target.closest('#joystick,#jump,#attack,#hotbar');if(!el)return;e.preventDefault();e.stopImmediatePropagation();moving=el;const r=el.getBoundingClientRect();offsetX=e.clientX-r.left-r.width/2;offsetY=e.clientY-r.top-r.height/2;el.setPointerCapture(e.pointerId);},true);document.addEventListener('pointermove',e=>{if(!moving)return;e.preventDefault();e.stopImmediatePropagation();const x=I.clamp((e.clientX-offsetX)/innerWidth*100,5,95),y=I.clamp((e.clientY-offsetY)/innerHeight*100,8,92);this.g.settings.layout={...this.g.settings.layout,[moving.id]:{x,y}};this.applyControls();},true);for(const type of ['pointerup','pointercancel'])document.addEventListener(type,e=>{if(moving){e.stopImmediatePropagation();moving=null;}},true);$('control-reset').onclick=()=>{this.g.setSettings({layout:{}});};$('control-done').onclick=()=>{this.editingControls=false;document.body.classList.remove('editing-controls');$('control-editor').classList.add('hidden');this.g.setSettings({layout:this.g.settings.layout});if(!this.g.active){$('hud').classList.add('hidden');$('menu').classList.remove('hidden');}this.showSettings();};}
  showHelp(){this.open('Как играть','help','ВСЁ НАЧИНАЕТСЯ С ПЕРВОГО БЛОКА');const rows=[['Движение','Джойстик слева. Для обзора проводи пальцем по свободной правой части экрана. Полный наклон вперёд включает бег, если он разрешён в настройках. Можно смотреть, двигая палец по удерживаемой кнопке действия.'],['Добыча','Выбери кирку или топор и удерживай единственную кнопку «Копать». Наведи прицел на блок: кольцо показывает прогресс.'],['Строительство','Выбери блок и нажми атаку, чтобы поставить его на выбранную поверхность. Блоки не ставятся внутри персонажа.'],['Сражения','Огнестрельное оружие расходует патроны и перезаряжается автоматически при пустом магазине. Лук и арбалет используют стрелы, гранаты взрываются. Посохи используют ману через ту же кнопку действия.'],['Рюкзак','Кнопка сумки сверху: предметы, рецепты и призыв боссов. Ресурсы с побеждённых врагов собираются автоматически.'],['Уровни и боссы','Опыт дают победы, добыча руды и новые области. В рюкзаке открой «Боссы»: уровень → победа над предыдущим → создание реликвии → призыв.'],['Выживание','Еда восстанавливает сытость. Зелье лечит. При высокой сытости здоровье медленно восстанавливается. Мир сохраняется каждые 25 секунд.'],['Творчество','Ресурсы бесконечны, урон отключён. Дважды нажми прыжок для полёта, удерживай его для подъёма, потяни палец вниз по кнопке для снижения.'],['Друзья','Начни игру, открой паузу и создай комнату. Друг на той же Wi-Fi сети вводит твой IPv4-адрес. Интернет-сервера в этой версии нет.'],['На компьютере','WASD — ходьба, мышь — обзор, Space — прыжок, Shift — бег, 1–8 — предметы, Q/E — стихии, R — перезарядка, B — рюкзак, Esc — пауза.']];$('modal-content').innerHTML=rows.map(([k,v])=>`<div class="help-row"><span>${k}</span><p>${v}</p></div>`).join('');}
  showFriends(){this.open('Вместе на рубеже','friends','КООПЕРАТИВ · ОДНА СЕТЬ WI-FI');const n=this.g.network;$('modal-content').innerHTML=`<p>Оба телефона должны быть в одной Wi-Fi сети. Хозяин запускает свой мир и открывает комнату; друзья вводят его адрес. Поддерживается хозяин и до трёх гостей.</p><div class="network-status" id="room-status">${esc(n.status)}</div><div class="network-actions"><button id="host-room" class="primary">СОЗДАТЬ КОМНАТУ</button><button id="stop-room" class="mini-button">Отключиться</button></div><div class="setting-row"><label>Адрес хозяина<small>IPv4, например 192.168.1.5</small></label><input id="room-address" type="text" placeholder="192.168.1.5" maxlength="15" inputmode="decimal"></div><button id="join-room" class="primary">ПРИСОЕДИНИТЬСЯ <span>→</span></button><p class="notice">Мир и противников рассчитывает хозяин. Мир сохраняется на его телефоне. Кооператив — экспериментальный; подключение двух физических телефонов нужно проверить отдельно. Во время комнаты хозяину следует оставаться в игре.</p>`;$('host-room').onclick=()=>n.host();$('stop-room').onclick=()=>{n.stop();this.updateNetwork();};$('join-room').onclick=()=>n.join($('room-address').value.trim());}
  updateNetwork(){const n=this.g.network;if(!n)return;$('network-label').classList.toggle('hidden',!n.role);$('network-label').textContent=n.role==='host'?'WI-FI · '+n.address+' · '+(Object.keys(this.g.remotePlayers).length+1)+'/4':n.role==='client'?'WI-FI · В МИРЕ ДРУГА':'';if($('room-status'))$('room-status').textContent=n.status;}
  loadMods(){try{const mods=JSON.parse(localStorage.getItem('iskra.mods')||'[]');this.g.mods=mods.slice(0,10);for(const m of this.g.mods)I.applyMod(m);}catch(e){this.g.mods=[];this.toast('Один из модов не прочитан.');}}
  importMod(text){try{this.g.mods=this.g.mods||[];if(this.g.mods.length>=10){this.toast('Поддерживается до 10 модов.');return;}const name=I.applyMod(text);this.g.mods.push(text);localStorage.setItem('iskra.mods',JSON.stringify(this.g.mods));this.toast('Мод включён: '+name);if(this.modalType==='mods')this.showMods();}catch(e){this.toast('Мод не загружен: '+e.message);}}
  showMods(){this.open('Моды','mods','ТВОИ ПРАВИЛА · ТВОЙ АРСЕНАЛ');const names=(this.g.mods||[]).map(t=>{try{return JSON.parse(t).name;}catch(e){return 'Неизвестный мод';}});$('modal-content').innerHTML='<p>В этой версии моды — JSON-файлы, меняющие названия и характеристики оружия: урон, дальность, темп стрельбы, расход маны, поджог и заморозку.</p>'+names.map(n=>'<div class="mod-entry">✦ '+esc(n)+'</div>').join('')+'<button id="import-mod" class="primary">ЗАГРУЗИТЬ JSON-МОД <span>+</span></button><button id="reset-mods" class="subtle">Отключить все моды и перезапустить</button><p class="notice">Пример «Стихийный арсенал» находится в папке mods исходников. Полноценные моды с новыми биомами, моделями и скриптами — дальнейший этап разработки.</p>';$('import-mod').onclick=()=>{if(typeof Android!=='undefined'&&Android.importMod)Android.importMod();else $('mod-file').click();};$('reset-mods').onclick=()=>{this.g.save(true);localStorage.removeItem('iskra.mods');location.reload();};}
  showDeath(){this.open('Приключение продолжается','death','ТЫ ПАЛ, НО МИР ОСТАЛСЯ');$('modal-content').innerHTML=`<p>Ты можешь вернуться к лагерю. Постройки, собранные предметы и победы сохраняются.</p><div class="death-stats"><div><b>${this.g.kills}</b>ПРОТИВНИКОВ ПОБЕЖДЕНО</div><div><b>${this.g.bosses.length} / ${I.BOSS_IDS.length}</b>БОССОВ ПОВЕРЖЕНО</div></div><button id="respawn" class="primary">ВЕРНУТЬСЯ В МИР <span>→</span></button>`;$('modal-close').classList.add('hidden');$('respawn').onclick=()=>{$('modal-close').classList.remove('hidden');this.g.respawn();};}
}
I.UI=UI;I.icon=icon;
try{window.game=new I.Game($('world'));game.network=new I.Network(game);new I.UI(game);window.nativeMod=text=>game.ui.importMod(text);window.nativePause=()=>{game.save(true);if(game.active&&!game.modal)game.ui.showPause();};window.nativeBack=()=>{if(game.modal&&game.active)game.ui.closeModal();else if(game.active)game.ui.showPause();else if(game.ui.modalType)game.ui.closeModal();else if(typeof Android!=='undefined')Android.exit();};}catch(e){$('boot').innerHTML='<div class="brand-small">ИСКРА</div><p style="max-width:500px;text-align:center">'+esc(e.message)+'</p>';console.error(e);}
})(ISKRA);
