'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..');global.window=global;global.innerWidth=844;global.innerHeight=390;global.requestAnimationFrame=()=>{};
const storage=new Map();global.localStorage={getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)};
for(const f of ['content.js','world.js'])vm.runInThisContext(fs.readFileSync(path.join(root,'game',f),'utf8'));
ISKRA.Renderer=class{resize(){}freeChunk(){}mesh(){}render(){}};
vm.runInThisContext(fs.readFileSync(path.join(root,'game/game.js'),'utf8'));
function element(id,rect={left:20,top:230,width:124,height:124}){return {id,offsetWidth:rect.width,classes:new Set(),style:{setProperty(k,v){this[k]=v;}},getBoundingClientRect:()=>rect,setPointerCapture(){},closest(selector){return selector==='#'+id||selector==='button'&&['attack','jump'].includes(id)?this:null;},classList:{add(){},remove(){}}};}
const elements={joystick:element('joystick'),'joy-knob':element('joy-knob'),world:element('world'),attack:element('attack'),jump:element('jump')};
global.document={getElementById:id=>elements[id],addEventListener(){}};global.addEventListener=()=>{};
vm.runInThisContext(fs.readFileSync(path.join(root,'game/controls.js'),'utf8'));
let checks=0;const test=(name,fn)=>{fn();checks++;console.log('PASS',name);};
test('radial joystick deadzone, proportional speed, diagonal normalization',()=>{const s=ISKRA.Stick.sample;assert.equal(s(1,1,50,.06).amount,0);const near=s(8,0,50,.06),far=s(35,0,50,.06);assert.ok(near.x>0&&near.x<far.x);const diag=s(100,-100,50,.06);assert.ok(Math.abs(Math.hypot(diag.x,diag.z)-1)<1e-9);assert.ok(Math.abs(diag.x-diag.z)<1e-9);assert.ok(Math.abs(Math.hypot(diag.kx,diag.ky)-50)<1e-9);});
const g=new ISKRA.Game({});g.settings.sound=false;g.start('creative');const c=new ISKRA.TouchControls(g);
const event=(id,target,x,y)=>({pointerId:id,pointerType:'touch',target,clientX:x,clientY:y,preventDefault(){}});
test('movement, look, attack and jump have independent touch owners',()=>{
 c.down(event(1,elements.joystick,82,292));c.down(event(2,elements.world,500,160));c.down(event(3,elements.attack,780,290));c.down(event(4,elements.jump,700,290));
 c.move(event(1,elements.joystick,82,240));const yaw=g.player.yaw;c.move(event(2,elements.world,540,160));assert.ok(g.player.yaw>yaw);assert.ok(g.input.z>.99);assert.ok(g.input.attack&&g.input.jump);c.up({pointerId:2});assert.ok(g.input.z>.99&&g.input.attack);c.up({pointerId:3});assert.equal(g.input.attack,false);assert.equal(g.input.jump,true);assert.ok(g.input.z>.99);c.up({pointerId:4});assert.equal(g.input.jump,false);c.up({pointerId:1});assert.equal(Math.abs(g.input.z),0);
});
test('two-thumb play can aim by dragging held action without releasing fire',()=>{const yaw=g.player.yaw;c.down(event(30,elements.joystick,82,240));c.down(event(31,elements.attack,780,290));c.move(event(31,elements.attack,740,270));assert.ok(g.input.attack);assert.ok(g.player.yaw<yaw);assert.ok(g.input.z>.9);c.up({pointerId:31});assert.ok(g.input.z>.9);c.up({pointerId:30});});
test('second movement finger cannot replace owner; cancel/reset release input',()=>{c.down(event(10,elements.joystick,82,240));c.down(event(11,elements.joystick,82,340));assert.equal(c.owners.move,10);assert.ok(g.input.z>0);c.down(event(12,elements.attack,780,290));c.reset();assert.equal(c.points.size,0);assert.equal(Math.abs(g.input.z),0);assert.equal(g.input.attack,false);g.modal=true;c.down(event(13,elements.joystick,82,240));assert.equal(c.points.size,0);g.modal=false;});
test('floating joystick starts at finger and follows any direction',()=>{g.settings.stickMode='floating';c.down(event(20,elements.world,100,300));assert.equal(c.owners.move,20);assert.equal(g.input.x,0);c.move(event(20,elements.world,155,300));assert.ok(g.input.x>.99);assert.equal(Math.abs(g.input.z),0);c.up({pointerId:20});g.settings.stickMode='fixed';});
test('camera sensitivity is consistent for equal fractions of different screens',()=>{g.player.yaw=0;g.aim(39,0,true);const a=g.player.yaw;global.innerWidth=1688;global.innerHeight=780;g.player.yaw=0;g.aim(78,0,true);assert.ok(Math.abs(g.player.yaw-a)<1e-9);global.innerWidth=844;global.innerHeight=390;g.settings.invert=true;g.player.pitch=0;g.aim(0,20,true);assert.ok(g.player.pitch>0);g.settings.invert=false;});
test('one action dispatches tool, sword, firearm, staff and block',()=>{const saved={mine:g.mine,hitMelee:g.hitMelee,fireWeapon:g.fireWeapon,place:g.place,findHit:g.findHit};let calls=[];g.mine=()=>calls.push('mine');g.hitMelee=()=>calls.push('melee');g.fireWeapon=id=>calls.push(id);g.place=()=>calls.push('place');g.findHit=()=>({});g.cooldown=0;g.hotbar=['pick','sword','rifle','fire','frost','dirt','wood','pistol'];for(const [slot,label] of [[0,'Копать'],[1,'Удар'],[2,'Огонь'],[3,'Заклинание'],[4,'Заклинание'],[5,'Поставить']]){g.selectSlot(slot);g.cooldown=0;assert.equal(g.actionInfo().label,label);g.attack(.02);}assert.deepEqual(calls,['mine','melee','rifle','fire','frost','place']);Object.assign(g,saved);});
test('missed melee strike animates; empty magazine reload preserves held attack',()=>{g.enemies=[];g.player.pitch=.8;g.cooldown=0;g.hitMelee(ISKRA.ITEMS.sword);assert.ok(g.swing>0);g.mode='survival';g.slot=7;g.inventory.ammo=40;g.magazines.pistol=0;g.input.attack=true;g.cooldown=0;g.attack(.02);assert.ok(g.reloading);assert.equal(g.input.attack,true);g.selectSlot(3);assert.equal(g.reloading,null);});
test('old layout is migrated and player preferences survive',()=>{storage.set('iskra.settings',JSON.stringify({version:2,layout:{spells:{x:50,y:50}},leftHand:true,sensitivity:1.25}));const next=g.readSettings();assert.deepEqual(next.layout,{});assert.equal(next.leftHand,true);assert.equal(next.sensitivity,1.25);assert.equal(next.version,3);});
test('reported frame time reflects a stalled frame instead of a 20 FPS floor',()=>{g.update=()=>{};g.renderer.render=()=>{};g.lastTime=100;g.fps=60;g.loop(600);assert.equal(g.frameMS,500);assert.ok(Math.abs(g.fps-(60*.92+2*.08))<1e-9);});
console.log(`\n${checks} mobile input checks passed.`);
