'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..');
// The same GL recorder powers real EGL frame replay and these upload/visibility checks.
const source=fs.readFileSync(path.join(__dirname,'capture-frame.cjs'),'utf8').split('const weapon=')[0].replace("path.resolve(__dirname,'..')",JSON.stringify(root));
const {gl,buffers}=new Function('require',source+'\nreturn {gl,buffers};')(require),I=ISKRA;
const renderer=new I.Renderer({width:1280,height:720,getContext:()=>gl});let checks=0;const test=(name,fn)=>{fn();checks++;console.log('PASS',name);};
test('frustum rejects behind/side geometry and accepts front after turning',()=>{const M=I.Matrix,projection=M.perspective(Math.PI/2,1,.1,100),a=M.planes(M.multiply(projection,M.view([0,0,0],0,0)));assert.ok(M.visible(a,[-1,-1,-12],[1,1,-10]));assert.equal(M.visible(a,[-1,-1,10],[1,1,12]),false);assert.equal(M.visible(a,[40,-1,-12],[42,1,-10]),false);const b=M.planes(M.multiply(projection,M.view([0,0,0],Math.PI/2,0)));assert.ok(M.visible(b,[10,-1,-1],[12,1,1]));});
test('chunk construction yields and discards a mesh edited during construction',()=>{const w=new I.World(),c=w.chunk(24,24);w.set(388,40,388,14);renderer.stepMeshes(w,[c],0);assert.ok(c.dirty);assert.ok(renderer.meshTask);w.set(388,40,388,0);let count=0;while(c.dirty&&count++<1000)renderer.stepMeshes(w,[c],1);assert.ok(count<1000);assert.ok(c.mesh);const data=buffers.get(c.mesh.buffer.id);for(let k=1;k<data.length;k+=I.Mesh.STRIDE)assert.ok(data[k]<40);});
test('surface cache invalidates for building, removal and foliage queries',()=>{const w=new I.World();assert.equal(w.surface(384,384),18);w.set(384,45,384,3);assert.equal(w.surface(384,384),46);w.set(384,45,384,0);assert.equal(w.surface(384,384),18);w.set(384,35,384,6);assert.equal(w.surface(384,384),36);assert.equal(w.surface(384,384,true),18);});
test('moving enemies and held weapon reuse geometry without uploads each frame',()=>{const g=new I.Game({width:1280,height:720,getContext:()=>gl});g.settings.sound=false;g.active=true;g.modal=false;g.slot=2;g.hotbar[2]='rifle';g.enemies=[];g.spawnEnemy('wolf',384,376);g.spawnEnemy('golem',388,375);g.spawnEnemy('root',390,367);g.visible=[];g.target=null;g.renderer.render(g);const cached=g.renderer.modelCache.size;let builds=0,uploads=0;const oldHeld=I.Models.held,oldCreature=I.Models.creature,oldUpload=gl.bufferData;I.Models.held=(...args)=>{builds++;return oldHeld(...args);};I.Models.creature=(...args)=>{builds++;return oldCreature(...args);};gl.bufferData=(...args)=>{uploads++;return oldUpload(...args);};for(let k=0;k<60;k++){g.time+=.016;g.player.moving=true;g.enemies[0].x+=.002;g.enemies[0].freeze=k%2;g.renderer.render(g);}assert.equal(builds,0);assert.equal(uploads,0);assert.equal(g.renderer.modelCache.size,cached);I.Models.held=oldHeld;I.Models.creature=oldCreature;gl.bufferData=oldUpload;});
test('all original creature and held models contain finite geometry',()=>{for(const id of Object.keys(I.ENEMIES)){const out=[];I.Models.creature(out,{type:id,id:0,x:0,y:0,z:0},0);assert.ok(out.length>0,id);assert.ok(out.every(Number.isFinite),id);}for(const [id,item] of Object.entries(I.ITEMS)){if(item.kind==='resource')continue;const out=[];I.Models.held(out,{selectedItem:()=>id,time:0,player:{moving:false},cooldown:0,flash:0,reloading:null});assert.ok(out.length>0,id);assert.ok(out.every(Number.isFinite),id);}});
test('adaptive resolution recovers while fixed resolution remains exact',()=>{renderer.resolution='auto';renderer.adaptive=true;renderer.autoScale=1;for(let k=0;k<360;k++)renderer.adapt(50,60,true);assert.ok(renderer.autoScale<1);const low=renderer.autoScale;for(let k=0;k<900;k++)renderer.adapt(16.7,60,true);assert.ok(renderer.autoScale>low);renderer.resolution='540';renderer.adapt(100,60,true);renderer.resize();assert.equal(renderer.canvas.height,540);});
console.log(`\n${checks} renderer checks passed.`);
